import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.4";

const ALLOWED_ORIGIN = Deno.env.get("ALLOWED_ORIGINS")?.split(",")[0]?.trim() || "*";
const corsHeaders = {
  "Access-Control-Allow-Origin": ALLOWED_ORIGIN,
  "Vary": "Origin",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

function jsonResponse(payload: unknown, status: number) {
  return new Response(JSON.stringify(payload), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });
  if (req.method !== "POST") return jsonResponse({ error: "Method not allowed" }, 405);

  const authHeader = req.headers.get("Authorization");
  if (!authHeader?.startsWith("Bearer ")) {
    return jsonResponse({ error: "Unauthorized" }, 401);
  }

  // Deliberately use the caller JWT instead of service_role. The database RPC
  // validates role/tenant ownership and executes the complete restore atomically.
  const supabaseUser = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_ANON_KEY")!,
    { global: { headers: { Authorization: authHeader } } },
  );

  const { data: userData, error: userError } = await supabaseUser.auth.getUser();
  if (userError || !userData?.user) {
    return jsonResponse({ error: "Unauthorized" }, 401);
  }

  let body: { tables?: Record<string, unknown[]> };
  try {
    body = await req.json();
  } catch {
    return jsonResponse({ error: "Invalid JSON" }, 400);
  }

  if (!body?.tables || typeof body.tables !== "object" || Array.isArray(body.tables)) {
    return jsonResponse(
      { error: "Invalid backup format. Expected { tables: { ... } }" },
      400,
    );
  }

  // Audit logs are generated by database triggers. Importing user-supplied audit
  // rows would make the trail forgeable, so legacy backups ignore that table.
  const { obra_audit_log: _ignoredAuditLog, ...restorableTables } = body.tables;

  const payloadBytes = new TextEncoder().encode(JSON.stringify(restorableTables)).byteLength;
  if (payloadBytes > 10 * 1024 * 1024) {
    return jsonResponse({ error: "Backup payload too large (max 10MB)" }, 413);
  }

  const { data, error } = await supabaseUser.rpc("restore_user_backup", {
    p_tables: restorableTables,
  });

  if (error) {
    const forbidden = error.code === "42501";
    const disabled = error.code === "0A000";
    return jsonResponse(
      {
        error: forbidden
          ? "Forbidden"
          : disabled
            ? "Backup restore temporarily unavailable"
            : "Backup restore failed",
        details: error.message,
      },
      forbidden ? 403 : disabled ? 503 : 400,
    );
  }

  return jsonResponse(data, 200);
});
